#!/usr/bin/env node
/* eslint-disable global-require, @typescript-eslint/no-require-imports */

/**
 * Output Folder Setup Script
 * Creates organized folder structure for builds and game files
 */

// eslint-disable-next-line @typescript-eslint/no-var-requires
const fs = require('fs');
// eslint-disable-next-line @typescript-eslint/no-var-requires
const path = require('path');

const colors = {
  reset: '\x1b[0m',
  cyan: '\x1b[36m',
  red: '\x1b[31m',
  green: '\x1b[32m',
  blue: '\x1b[34m'
};

function log(level, message) {
  const levelColors = {
    'INFO': colors.cyan,
    'ERROR': colors.red,
    'SUCCESS': colors.green,
    'FOLDER': colors.blue
  };
  
  const color = levelColors[level] || colors.reset;
  console.log(`${color}[${level}]${colors.reset} ${message}`);
}

function setupOutput() {
  const outputDir = 'output';
  const structure = {
    'bin': 'Compiled executables (compile.exe, etc)',
    'builds': 'Game ROM files (.gbc, .gb)',
    'dist': 'Compiled TypeScript & JavaScript',
    'obj': 'Object files and intermediate builds',
    'docs': 'Documentation and guides',
    'source': 'Source code and tools'
  };

  log('INFO', 'Setting up output folder structure...');
  console.log('');

  // Create main output directory
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
    log('SUCCESS', `Created ${outputDir}/`);
  }

  // Create subdirectories
  for (const [dir, description] of Object.entries(structure)) {
    const fullPath = path.join(outputDir, dir);
    if (!fs.existsSync(fullPath)) {
      fs.mkdirSync(fullPath, { recursive: true });
      log('FOLDER', `${dir}/`.padEnd(15) + `- ${description}`);
    }
  }

  // Create README in output folder
  const readmeContent = `# Output Folder Structure

## Folder Organization

\`\`\`
output/
├── bin/              Compiled executables
│   └── compile.exe   Build tool (generated by npm run build-exe)
├── builds/           Game ROM files
│   ├── LabyrinthOfTheDragon.gbc   Main game ROM
│   └── *.gbc         Additional game builds
├── dist/             Compiled output
│   └── index.js      Compiled TypeScript/JavaScript
├── obj/              Object files
│   └── *.asm         Assembly listings
├── docs/             Documentation
│   ├── FEATURE_TESTING_GUIDE.md
│   ├── API_INTEGRATION_GUIDE.md
│   └── ...           Other documentation
└── source/           Source code
    ├── ts/           TypeScript source
    ├── c/            C source code
    └── js/           JavaScript source

\`\`\`

## How to Build

1. **Build Everything:**
   \`\`\`
   npm run build-exe
   .\\compile.exe all
   \`\`\`

2. **Build Game Only:**
   \`\`\`
   .\\compile.exe game
   \`\`\`

3. **Organize Output:**
   \`\`\`
   npm run setup-output
   \`\`\`

## Output Files

After building, you'll find:
- **compile.exe** → output/bin/compile.exe
- **LabyrinthOfTheDragon.gbc** → output/builds/LabyrinthOfTheDragon.gbc
- **Compiled JS** → output/dist/
- **Documentation** → output/docs/
`;

  fs.writeFileSync(path.join(outputDir, 'README.md'), readmeContent);
  log('SUCCESS', 'Created output/README.md');

  console.log('');
  log('SUCCESS', 'Output folder structure ready!');
  log('INFO', 'Run: npm run build-exe && .\\compile.exe all');
}

setupOutput();
